version: "3"
services:
  node_be:
    container_name: fml-be
    restart: unless-stopped
    build: .
    ports:
      - "2200:2200"
    links:
      - db
    env_file: .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    # environment:
    #   - MONGO_URI=$MONGO_URI
    #   - PORT=$PORT
    # networks:
    #   - app-network
    # command: ./wait-for.sh falcon-db:5517 -- /home/node/app/node_modules/.bin/nodemon index.js
  db:
    container_name: fml-db
    image: mongo:4.1.8-xenial
    restart: unless-stopped
    volumes:  
      - dbdata:/data/db 
    ports:
      - "27017:27017"
    # command: mongod --port 5515
    # env_file: .env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    # networks:
    #   - app-network
      
# networks:
#   app-network:
#     driver: bridge

volumes:
  dbdata:
  node_modules:  